markdown: kramdown
mathjax: true

highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: aoshu
author: "aoshu"
email: winfirm#163.com
name: "aoshu个人博客"
url: # http://www.panxw.com
domain: # www.panxw.com
all_categories: [
["recent_post", "最新文章","/recent_post.html"],
["xc", "行程","/posts/xc.html"], 
["sl", "数论","/posts/sl.html"],
["jh", "几何","/posts/jh.html"], 
["js", "计数","/posts/js.html"], 
["yyt", "应用题","/posts/yyt.html"], 
["jiSuan", "计算","/posts/jiSuan.html"], 
["zt", "杂题","/posts/zt.html"],
["archive", "存档","/archives.html"], 
["FAQS", "帮助","/faqs.html"], 
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
